spring.application.name=rwhiskey.api
spring.profiles.active=local
spring.config.import=optional:file:.env.local[.properties]
server.port=${PORT:8080}

# DB Mapping (Values from .env or Railway env vars)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=4

# Redis Mapping
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Resend Mapping
resend.api.key=${RESEND_API}
resend.from.email=${RESEND_DOMAIN}

# Session Common
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# JPA Common
spring.jpa.database=postgresql

# App Security Defaults (Will be overwritten by profiles)
app.security.csrf.enabled=true
app.cors.allowed-origins=https://turt1e18.work,https://www.turt1e18.work
